<?php
if ($language == 'english') {
    ?>
    <option>1</option>
    <option>2</option>
    <option>3</option>
    <option>4</option>
    <option>5</option>
    <option>6</option>
    <option>7</option>
    <option>8</option>
    <option>9</option>
    <option>10</option>
    <option>11</option>
    <option>12</option>
    <option>13</option>
    <option>14</option>
    <option>15</option>
    <option>16</option>
    <option>17</option>
    <option>18</option>
    <option>19</option>
    <option>20</option>
    <option>21</option>
    <option>22</option>
    <option>23</option>
    <option>24</option>
    <option>25</option>
    <option>26</option>
    <option>27</option>
    <option>28</option>
    <option>29</option>
    <option>30</option>
    <option>31</option>
    <?php
} else {
    ?>
    <option>١</option>
    <option>٢</option>
    <option>٣</option>
    <option>٤</option>
    <option>٥</option>
    <option>٦</option>
    <option>٧</option>
    <option>٨</option>
    <option>٩</option>
    <option>١٠</option>
    <option>١١</option>
    <option>١٢</option>
    <option>١٣</option>
    <option>١٤</option>
    <option>١٥</option>
    <option>١٦</option>
    <option>١٧</option>
    <option>١٨</option>
    <option>١٩</option>
    <option>٢٠</option>
    <option>٢١</option>
    <option>٢٢</option>
    <option>٢٣</option>
    <option>٢٤</option>
    <option>٢٥</option>
    <option>٢٦</option>
    <option>٢٧</option>
    <option>٢٨</option>
    <option>٢٩</option>
    <option>٣٠</option>
    <option>٣١</option>
    <?php
}
?>